### PR TITLE
ROM cleanup

### PR DESCRIPTION
**Pull request by Kolcha**
removed a lot of unnecessary packages

### CODE REVIEW

**Comment by Kolcha** [comment]
memory usage before cleanup:
```
Total RAM: 2,058,448K (status normal)
 Free RAM: 1,609,809K (  134,413K cached pss +   107,464K cached kernel + 1,367,932K free)
 Used RAM:   347,933K (  286,181K used pss +    61,752K kernel)
 Lost RAM:   100,702K
     ZRAM:         4K physical used for         0K in swap (  307,196K total swap)
   Tuning: 128 (large 512), oom   184,320K, restore limit    61,440K (high-end-gfx)
```
memory usage after cleanup:
```
Total RAM: 2,058,448K (status normal)
 Free RAM: 1,651,606K (   84,982K cached pss +   247,608K cached kernel + 1,319,016K free)
 Used RAM:   296,556K (  244,912K used pss +    51,644K kernel)
 Lost RAM:   110,282K
     ZRAM:         4K physical used for         0K in swap (  307,196K total swap)
   Tuning: 128 (large 512), oom   184,320K, restore limit    61,440K (high-end-gfx)
```

system image size decreased by ~75MB

**Comment by chakaponden** [comment]
When you removed tts package, you should disable tts support in Settings package as well.

**Comment by chakaponden** [comment]
As well as you decided to remove telephony packages, it's a good practice to tell other aosp modules, that you have no telephony any more by passing: 
_config.disable_telephony=true_ via **PRODUCT_PROPERTY_OVERRIDES**.

You can achieve better results by using the same strategy for the other packages/services you disabled.

**Comment by Kolcha** [comment]
there is no such key *config.disable_telephony* since Android 6. last Android version that has this key is Android 5.

**Comment by chakaponden** [comment]
What about:

-    config.disable_rtt=true 
-    config.disable_systemui=true
-    config.disable_mediaproj=true 
-    config.disable_searchmanager=true 
-    config.disable_samplingprof=true 
-    config.disable_consumerir=true 
-    config.disable_vrmanager=true 
-    config.disable_cameraservice=true 
-    config.enable_java_radio=false 
-    config.disable_renderscript=true 
-    drm.service.enabled=false 

Also:
-    fw.show_multiuserui=false 
-    ro.lockscreen.disable.default=true 
-    fw.power_user_switcher=false

**Comment by chakaponden** [comment]
What about:

-    config.disable_rtt=true 
-    config.disable_systemui=true
-    config.disable_mediaproj=true 
-    config.disable_searchmanager=true 
-    config.disable_samplingprof=true 
-    config.disable_consumerir=true 
-    config.disable_vrmanager=true 
-    config.enable_java_radio=false 
-    config.disable_renderscript=true 
-    drm.service.enabled=false 

Also:
-    fw.show_multiuserui=false 
-    ro.lockscreen.disable.default=true 
-    fw.power_user_switcher=false

**Pull request merged**
